import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(),],
})


// const translations = {
//   hindi: {
//     code: "hi",
//     name: "हिंदी",
//     home: "मुख्य पृष्ठ",
//     about: "हमारे बारे में", 
//     services: "सेवाएं",
//     contact: "संपर्क",
//     loginRegister: "लॉगिन/रजिस्टर",
//     language: "भाषा",
//     empoweringFarmers: "एक स्थायी भविष्य के लिए",
//     farmersEmpowerment: "किसानों को सशक्त बनाना",
//     heroDescription: "समृद्धि के लिए पारंपरिक ज्ञान को आधुनिक तकनीक से जोड़ना किसानों के लिए और सभी के लिए स्थायी खाद्य प्रणाली",
//     exploreServices: "हमारी सेवाओं का अन्वेषण करें",
//     governmentSchemes: "सरकारी योजनाएं",
//     aboutFarmerSetu: "फार्मर सेतु के बारे में",
//     aboutDescription: "हम नवाचार के माध्यम से कृषि को बदलने के लिए समर्पित हैं, किसानों को अत्याधुनिक तकनीक, सरकारी सहायता और समृद्ध भविष्य के लिए स्थायी कृषि पद्धतियों से जोड़ना।",
//     getInTouch: "संपर्क में रहें",
//     quickLinks: "त्वरित लिंक",
//     certifications: "प्रमाणपत्र",
//     ourMission: "हमारा मिशन",
//     missionDescription: "अत्याधुनिक तकनीक के साथ किसानों को सशक्त बनाकर कृषि में क्रांति लाना, सरकारी योजनाओं तक निर्बाध पहुंच, और स्थायी कृषि पद्धतियां जो उत्पादकता बढ़ाती हैं और भावी पीढ़ियों के लिए हमारे पर्यावरण का संरक्षण करती हैं।",
//     innovation: "नवाचार",
//     support: "सहायता",
//     sustainability: "स्थिरता",
//     farmersConnected: "किसान जुड़े",
//     statesCovered: "राज्य कवर किए गए",
//     satisfactionRate: "संतुष्टि दर",
//     cropManagement: "फसल प्रबंधन",
//     financialAid: "वित्तीय सहायता",
//     digitalTools: "डिजिटल उपकरण",
//     training: "प्रशिक्षण"
//   },
//   english: {
//     code: "en",
//     name: "English",
//     home: "Home",
//     about: "About",
//     services: "Services", 
//     contact: "Contact",
//     loginRegister: "Login/Register",
//     language: "Language",
//     empoweringFarmers: "for a Sustainable Future",
//     farmersEmpowerment: "Empowering Farmers",
//     heroDescription: "Bridging traditional wisdom with modern technology to create prosperity for farmers and sustainable food systems for everyone",
//     exploreServices: "Explore Our Services",
//     governmentSchemes: "Government Schemes",
//     aboutFarmerSetu: "About FarmerSetu",
//     aboutDescription: "We are dedicated to transforming agriculture through innovation, connecting farmers with cutting-edge technology, government support, and sustainable farming practices for a prosperous future.",
//     getInTouch: "Get In Touch",
//     quickLinks: "Quick Links",
//     certifications: "Certifications",
//     ourMission: "Our Mission",
//     missionDescription: "To revolutionize agriculture by empowering farmers with cutting-edge technology, seamless access to government schemes, and sustainable farming practices that boost productivity while preserving our environment for future generations.",
//     innovation: "Innovation",
//     support: "Support",
//     sustainability: "Sustainability",
//     farmersConnected: "Farmers Connected",
//     statesCovered: "States Covered",
//     satisfactionRate: "Satisfaction Rate",
//     cropManagement: "Crop Management",
//     financialAid: "Financial Aid",
//     digitalTools: "Digital Tools",
//     training: "Training"
//   },
//   telugu: {
//     code: "te",
//     name: "తెలుగు",
//     home: "మొదటి పేజీ",
//     about: "మా గురించి",
//     services: "సేవలు",
//     contact: "సంప్రదింపులు",
//     loginRegister: "లాగిన్/రిజిస్టర్",
//     language: "భాష",
//     empoweringFarmers: "స్థిర భవిష్యత్తు కోసం",
//     farmersEmpowerment: "రైతులను శక్తివంతం చేయడం",
//     heroDescription: "రైతుల కోసం సంపద మరియు అందరికీ స్థిర ఆహార వ్యవస్థలను సృష్టించడానికి సాంప్రదాయ జ్ఞానాన్ని ఆధునిక సాంకేతికతతో కలుపుట",
//     exploreServices: "మా సేవలను అన్వేషించండి",
//     governmentSchemes: "ప్రభుత్వ పథకాలు",
//     aboutFarmerSetu: "ఫార్మర్ సేతు గురించి",
//     aboutDescription: "మేము నవీనత ద్వారా వ్యవసాయాన్ని మార్చడానికి అంకితం చేసుకున్నాము, రైతులను అత్యాధునిక సాంకేతికత, ప్రభుత్వ మద్దతు మరియు సంపన్న భవిష్యత్తు కోసం స్థిర వ్యవసాయ పద్ధతులతో కలుపుట.",
//     getInTouch: "సంప్రదించండి",
//     quickLinks: "త్వరిత లింకులు",
//     certifications: "ధృవపత్రాలు",
//     ourMission: "మా లక్ష్యం",
//     missionDescription: "అత్యాధునిక సాంకేతికతతో రైతులను శక్తివంతం చేయడం ద్వారా వ్యవసాయంలో విప్లవం తేవడం, ప్రభుత్వ పథకాలకు నిరంతర ప్రవేశం మరియు భవిష్యత్ తరాలకు మా పర్యావరణాన్ని కాపాడుతూ ఉత్పాదకతను పెంచే స్థిర వ్యవసాయ పద్ధతులు.",
//     innovation: "నవీనత",
//     support: "మద్దతు",
//     sustainability: "స్థిరత్వం",
//     farmersConnected: "రైతులు అనుసంధానించబడ్డారు",
//     statesCovered: "రాష్ట్రాలు కవర్ చేయబడ్డాయి",
//     satisfactionRate: "సంతృప్తి రేటు",
//     cropManagement: "పంట నిర్వహణ",
//     financialAid: "ఆర్థిక సహాయం",
//     digitalTools: "డిజిటల్ సాధనాలు",
//     training: "శిక్షణ"
//   },
//   bengali: {
//     code: "bn",
//     name: "বাংলা",
//     home: "হোম",
//     about: "আমাদের সম্পর্কে",
//     services: "সেবাসমূহ",
//     contact: "যোগাযোগ",
//     loginRegister: "লগইন/রেজিস্টার",
//     language: "ভাষা",
//     empoweringFarmers: "একটি টেকসই ভবিষ্যতের জন্য",
//     farmersEmpowerment: "কৃষকদের ক্ষমতায়ন",
//     heroDescription: "কৃষকদের জন্য সমৃদ্ধি এবং সবার জন্য টেকসই খাদ্য ব্যবস্থা তৈরি করতে ঐতিহ্যবাহী জ্ঞানের সাথে আধুনিক প্রযুক্তির সেতুবন্ধন",
//     exploreServices: "আমাদের সেবা অন্বেষণ করুন",
//     governmentSchemes: "সরকারি পরিকল্পনা",
//     aboutFarmerSetu: "ফার্মার সেতু সম্পর্কে",
//     aboutDescription: "আমরা উদ্ভাবনের মাধ্যমে কৃষিকে রূপান্তরিত করার জন্য নিবেদিতপ্রাণ, কৃষকদের অত্যাধুনিক প্রযুক্তি, সরকারি সহায়তা এবং সমৃদ্ধ ভবিষ্যতের জন্য টেকসই কৃষি পদ্ধতির সাথে সংযুক্ত করি।",
//     getInTouch: "যোগাযোগ করুন",
//     quickLinks: "দ্রুত লিঙ্ক",
//     certifications: "সার্টিফিকেশন",
//     ourMission: "আমাদের মিশন",
//     missionDescription: "অত্যাধুনিক প্রযুক্তির সাথে কৃষকদের ক্ষমতায়ন করে কৃষিতে বিপ্লব আনা, সরকারি পরিকল্পনায় নির্বিঘ্ন প্রবেশাধিকার, এবং টেকসই কৃষি পদ্ধতি যা উৎপাদনশীলতা বৃদ্ধি করে এবং ভবিষ্যত প্রজন্মের জন্য আমাদের পরিবেশ সংরক্ষণ করে।",
//     innovation: "উদ্ভাবন",
//     support: "সহায়তা",
//     sustainability: "স্থায়িত্ব",
//     farmersConnected: "কৃষক সংযুক্ত",
//     statesCovered: "রাজ্য কভার করা হয়েছে",
//     satisfactionRate: "সন্তুষ্টির হার",
//     cropManagement: "ফসল ব্যবস্থাপনা",
//     financialAid: "আর্থিক সহায়তা",
//     digitalTools: "ডিজিটাল সরঞ্জাম",
//     training: "প্রশিক্ষণ"
//   }
// };
